name: Update README

on:
  push:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate directory listing
      run: |
        ls -l > directory_listing.txt

    - name: Update README.md
      run: |
        DIRECTORY_LISTING=$(< directory_listing.txt)
        awk -v var="$DIRECTORY_LISTING" '{gsub(/{{DIRECTORY_LISTING}}/, var)} 1' README.md > README.md.tmp && mv README.md.tmp README.md

    - name: Configure Git
      run: |
        git config --global user.name "Brandon-Roff"
        git config --global user.email "roffo@nerdy-technician.social"

    - name: Commit changes
      run: |
        git add README.md
        git commit -m "Update README with directory listing"
        git push https://github.com/${{ github.repository }}.git HEAD:main
